### ISSUE TITLE
Suggest: Dye things in cauldrons

### ISSUE THREAD

**Issue by donmor** [maxoduke/Potion-Cauldron#17]
Make cauldrons able to dye things like leather equipment, just like in BE.

**Comment by maxoduke** [comment]
i have thought about this, but changed by mind because:
1. mods that do this already exist: [cauldron dyeing](https://modrinth.com/mod/cauldron-dyeing) [cauldron expansion](https://modrinth.com/datapack/cauldron-expansion)
2. this mod is specifically focused on bringing parity of **potion cauldrons** from bedrock with some extra configurable features. if i were to add dyeing functionality, that'd be outside of the scope of this mod and i'd have to change the name of the mod too.
